source 'https://rubygems.org'
require 'json'
require 'open-uri'

gem 'github-pages'
gem 'jekyll'
gem 'jekyll-mentions'
gem 'jekyll-compose'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'jekyll-feed'
gem 'jekyll-swfobject'
gem 'jemoji'
gem 'html-proofer'
gem 'rouge'
gem 'pygments.rb'